@startuml ЖЦ банковской карты

state "ЖЦ банковской карты" as C {
    [*] --> Активная: Выдана клиенту

    state Активная {
    [*] --> Обычная
    Обычная : таймер = 3 года
    Обычная --> Премиум: изменен статус клиента
    Премиум : таймер = 5 лет
      
}

Активная --> Заблокированная: подозрительная активность
Заблокированная --> Активная: разблокировка
Активная --> Просроченная: таймаут
Активная --> Утерянная: запрос клиента
Утерянная --> Активная: карта найдена
Утерянная --> Заблокированная: таймаут
Утерянная : таймер 7 к.д.
note left of Утерянная
ждет реакции клиента
end note
Заблокированная --> Просроченная
Просроченная --> [*]

@enduml