@startuml ЖЦ банковской карты

state "Депозитный вклад" as Deposit {
    [*] --> Открытие
    Открытие --> Ожидание_активации: Заявка подана

    state Ожидание_активации {
    [*] --> Проверка_документов
    Проверка_документов --> Подтвержден: [Документы в порядке]
    Проверка_документов --> Отклонен: [Ошибки в документах]
    }
    Подтвержден --> Активный: Первый взнос внесен
    Активный --> Продленный: [Автопролонгация]
    Активный --> Завершен: [Срок истек]

    state Завершен {
    [*] --> Выплата_процентов
    Выплата_процентов --> Закрыт: [Средства возвращены]
   
    }
}

Отклонен --> [*]
Закрыт --> [*]

@enduml