@startuml
title Скоринг заявки поставщика
actor Поставщик
participant Программа
participant БД
participant Kafka
participant Скоринг
participant Уведомления
autonumber
Поставщик -> Программа: открыть форму заявки
activate Программа
Программа --> Поставщик: форма заявки
Поставщик -> Программа: отправить заполненную форму
alt все поля заполнены
Программа -> БД: проверить наличие поставщика
alt поставщик найден
Программа -> БД: проверить статус Поставщика
alt статус Партнер
Программа -> Поставщик: сообщение: компания уже участвует в программе 
else
Программа -> Поставщик: сообщение: компании отказано в участии 
end alt
else
Программа -> Программа: создать поставщика
end alt
else
Программа -> Поставщик: сообщение: заполните обязательные поля
end alt
Программа -> БД: сохранить нового поставщика
activate БД
БД --> Программа: успех
deactivate БД
Программа -> Kafka: опубликовать событие (новый поставщик)
activate Kafka
Скоринг -> Kafka: получить событие (новый поставщик)
activate Скоринг
Kafka --> Скоринг: событие (новый поставщик)
Скоринг -> Скоринг: оценить поставщика
Скоринг -> Kafka: опубликовать событие (оценка)
deactivate Скоринг
Программа -> Kafka: получить событие (оценка)
Kafka --> Программа: событие (оценка)
deactivate Kafka
alt белая зона
Программа -> Программа: присвоить Поставщику статус Партнера
else
alt черная зона
Программа -> Программа: присвоить Поставщику статус Отказ
else
Программа -> Программа: создать задачу оценки вручную
end alt
end alt
Программа -> БД: обновить поставщика
activate БД
БД --> Программа: успех
deactivate БД
Программа -> Уведомления: отправить событие оценки
deactivate Программа
activate Уведомления
Уведомления --> Поставщик: отправить результат обработки заявки
deactivate Уведомления
@enduml

