@startuml
start

:Клиент переходит на сайт;

if (Есть зарегистрированный аккаунт) then (да)
:Авторизация;
else (нет)
:Регистрация аккаунт;
endif

:Подтверждение учетных данных клиента;
:Поиск товара;
:Добавление товара в корзину;
:Выбор способа доставки и оплаты;

if (Товар в наличии) then (да)

label dummyLabel
label dummyLabel
label dummyLabel
label dummyLabel
label dummyLabel
label dummyLabel
label myLabel
:Оплата заказа;

fork
:Обработка платежа;
if (Успешный платёж) then (да)
:Генерация счетфактуры;
else (нет)
:Уведомление клиенту о проблеме с платежом;
if (Повторить попытку оплаты) then (нет)
fork
:Отмена заказа;
fork again
:Возврат денег клиенту;
end fork
stop
else (да) 
:Повторная оплата;
endif
endif

fork again
:Отправка задания складу;
:Сбор заказа на складе;
:Организация доставки выбранным клиентом способом;
end fork

else (нет)

:Уведомление о недоступности товара;
if (Выбран альтернативный товар) then (да)
:Добавление товара в корзину;
goto myLabel
else (нет)
:Удаление товара из корзины;
stop
endif

endif
:Обновление статуса заказа;
:Уведомление клиента об актуальном статусе;
stop

@enduml