@startuml 3.2
class Customer {
    - name: String
    - email: String
    + placeOrder(): void
}

class Order {
    - orderID: int
    - date: date
    + calculateTotal(): double
}

class PremiumCustomer {
    + getRewards(): void
}
Customer <|-- PremiumCustomer
Customer "1" -- "0..*" Order : places
@enduml