@startuml homework 6

class User {
    - userID: Integer
    - userName: String
    - profile: <reference> Profile
    + getUserDetails() : String
}

class Student {
    + getStudentInfo() : String
}

class Instructor {
    - department: <reference> Department
    + getInstuctorInfo() : String
}

class Course {
    - courseID: Integer
    - courseName: String
}

class Item {
    - itemID: Integer
    - itemName: String
    - price: Double
}

class PaymentProcessor {
    + processPayment() : Boolean
}

class Department {
    - deptID: Integer
    - deptName: String
    + getDepartmentInfo() : String
}

class Profile {
    - profileID: Integer
    - bio: String
    - avatarUrl: String
    + getProfileSummary() : String
}

class Enrollment {
    - enrollmentDate: Date
    - grade: String
}

Student "1" -- "0..*" Course: студент выбирает курс (ассоциация, 0..*)
Course "0..1" --> "1" Instructor: преподаватель назначается на курс
Course "1" *-- "1..*" Item: заказ содержит элементы (композиция, 1..*)
Course ..> PaymentProcessor: заказ использует процессор платежей (зависимость)
Instructor "1" --> "1" Department: сотрудник пренадлежит отделу (ассоциация, обязательная связь)
User ..> PaymentProcessor: пользователь инициирует платеж (зависимость)
User "1" --> "0..1" Profile: содержит профиль (ассоциация, 0..1)
User <|-- Student: наследование (студент, подтип пользователя)
User <|-- Instructor: наследование (преподаватель, подтип пользователя)
Student "1" -- "0..*" Enrollment: студент зачисляется на курсы (ассоциация, 0..*)
Enrollment "1" -- "1*" Course: зачисление относится к конкретному курсу (ассоциация, 1)
Course --> Department: курс предложен отделом (ассоциация, связь)

@enduml